---
title: "Proj_figures"
output: html_document
date: "2023-04-23"
---

This is a script created to analyze the data from Piehl et al. (2022). This script is for using the integrated cognitively impaired data to create the volcano plots, UMAP, and heatmap. 


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Install and load packages
library(Seurat)
library(SeuratData)
library(MAST)
library(ggplot2)
#BiocManager::install("EnhancedVolcano")
library(EnhancedVolcano)
```

```{r}
#load integrated cognitively impaired (10 individuals) data and creat an object
#load("/Users/noelmoore/Desktop/CI_integrated_data.rda")
cogimp<-CI_integrated_data
```

```{r}
head(Idents(cogimp))
Idents(object = cogimp) <- "cell_type"
head(Idents(cogimp))
```

```{r}
levels(cogimp)
```

CI
```{r}
markers1 <- FindMarkers(cogimp,  ident.1 = "Tem/Effector helper T cells", ident.2 = NULL, assay="RNA", test.use = "MAST")

markers1

EnhancedVolcano(markers1, x="avg_log2FC", y="p_val", lab=rownames(markers1), title = "Tem/Effector helper T cells")
```

```{r}
markers2 <- FindMarkers(cogimp,  ident.1 = "Tcm/Naive helper T cells", ident.2 = NULL, assay="RNA", test.use = "MAST")

EnhancedVolcano(markers2, x="avg_log2FC", y="p_val", lab=rownames(markers2), title = "Tcm/Naive helper T cells")
```

```{r}
markers3 <- FindMarkers(cogimp,  ident.1 = "Tem/Trm cytotoxic T cells", ident.2 = NULL, assay="RNA", test.use = "MAST")

EnhancedVolcano(markers3, x="avg_log2FC", y="p_val", lab=rownames(markers3), title = "Tem/Trm cytotoxic T cells")
```

```{r}
markers4 <- FindMarkers(cogimp,  ident.1 = "DC2", ident.2 = NULL, assay="RNA", test.use = "MAST")

EnhancedVolcano(markers4, x="avg_log2FC", y="p_val", lab=rownames(markers4), title = "DC2")
```

```{r}
markers5 <- FindMarkers(cogimp,  ident.1 = "DC", ident.2 = NULL, assay="RNA", test.use = "MAST")

EnhancedVolcano(markers5, x="avg_log2FC", y="p_val", lab=rownames(markers5), title = "DC")
```

```{r}
markers6 <- FindMarkers(cogimp,  ident.1 = "Regulatory T cells", ident.2 = NULL, assay="RNA", test.use = "MAST")

EnhancedVolcano(markers6, x="avg_log2FC", y="p_val", lab=rownames(markers6), title = "Regulatory T cells")
```

```{r}
markers7 <- FindMarkers(cogimp,  ident.1 = "Memory B cells", ident.2 = NULL, assay="RNA", test.use = "MAST")

EnhancedVolcano(markers7, x="avg_log2FC", y="p_val", lab=rownames(markers7), title = "Memory B cells")
```

```{r}
markers8 <- FindMarkers(cogimp,  ident.1 = "Type 1 helper T cells", ident.2 = NULL, assay="RNA", test.use = "MAST")

EnhancedVolcano(markers8, x="avg_log2FC", y="p_val", lab=rownames(markers8), title = "Type 1 helper T cells")
```

```{r}
markers9 <- FindMarkers(cogimp,  ident.1 = "CD16- NK cells", ident.2 = NULL, assay="RNA", test.use = "MAST")

EnhancedVolcano(markers9, x="avg_log2FC", y="p_val", lab=rownames(markers9), title = "CD16- NK cells")
```

```{r}
markers10 <- FindMarkers(cogimp,  ident.1 = "Classical monocytes", ident.2 = NULL, assay="RNA", test.use = "MAST")

EnhancedVolcano(markers10, x="avg_log2FC", y="p_val", lab=rownames(markers10), title = "Classical monocytes")
```

```{r}
markers11 <- FindMarkers(cogimp,  ident.1 = "pDC", ident.2 = NULL, assay="RNA", test.use = "MAST")

EnhancedVolcano(markers11, x="avg_log2FC", y="p_val", lab=rownames(markers11), title = "pDC")
```

```{r}
markers12 <- FindMarkers(cogimp,  ident.1 = "MAIT cells", ident.2 = NULL, assay="RNA", test.use = "MAST")

EnhancedVolcano(markers12, x="avg_log2FC", y="p_val", lab=rownames(markers12), title = "MAIT cells")
```

```{r}
markers13 <- FindMarkers(cogimp,  ident.1 = "NK cells", ident.2 = NULL, assay="RNA", test.use = "MAST")

EnhancedVolcano(markers13, x="avg_log2FC", y="p_val", lab=rownames(markers13), title = "NK cells")
```

```{r}
markers14 <- FindMarkers(cogimp,  ident.1 = "CD16+ NK cells", ident.2 = NULL, assay="RNA", test.use = "MAST")

EnhancedVolcano(markers14, x="avg_log2FC", y="p_val", lab=rownames(markers14), title = "CD16+ NK cells")
```

```{r}
markers15 <- FindMarkers(cogimp,  ident.1 = "Tcm/Naive cytotoxic T cells", ident.2 = NULL, assay="RNA", test.use = "MAST")

EnhancedVolcano(markers15, x="avg_log2FC", y="p_val", lab=rownames(markers15), title = "Tcm/Naive cytotoxic T cells")
```

```{r}
markers16 <- FindMarkers(cogimp,  ident.1 = "ILC3", ident.2 = NULL, assay="RNA", test.use = "MAST")

EnhancedVolcano(markers16, x="avg_log2FC", y="p_val", lab=rownames(markers16), title = "ILC3")
```

```{r}
markers17 <- FindMarkers(cogimp,  ident.1 = "Mono-mac", ident.2 = NULL, assay="RNA", test.use = "MAST")

EnhancedVolcano(markers17, x="avg_log2FC", y="p_val", lab=rownames(markers17), title = "Mono-mac")
```


```{r}
#create an object of the genes the authors used in the heatmap
features<-c("APOE", "BIN1", "MS4AGA", "PICALM", "CR1", "TREM2", "ABCA7", "PTK2B", "PLCG2", "SPI1", "SORL1", "CD2AP", "SLC24A4", "RIN3", "CASS4", "ADAM10", "HAVCR2", "SCIMP", "CLNK", "TNIP1", "ABCA1", "USP6NL", "INPP5D", "CD33", "WWOX", "ABI3", "APH1B", "HS3ST1", "CHRNE", "CCDC6", "KAT8")

#create the heatmap
DoHeatmap(cogimp, features = features, size=2) 
#Warning: The following features were omitted as they were not found in the scale.data slot for the integrated assay: KAT8, CHRNE, HS3ST1, APH1B, WWOX, INPP5D, USP6NL, ABCA1, TNIP1, CLNK, SCIMP, CASS4, SLC24A4, PLCG2, PTK2B, CR1, MS4AGA, APOE

```

```{r}
#create a UMAP of cogimp using outliers found with the Variable Features function 
cogimp<-RunUMAP(cogimp, features = VariableFeatures(cogimp), reduction.name = "umap")

DimPlot(cogimp, reduction = "umap")
```
